// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaqqbkwidpkntvomjgzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcXFia3dpZHBrbnR2b21qZ3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NjgzNjQsImV4cCI6MjA3NzA0NDM2NH0.-sCiXa2Xt_J0SIYrYynb2eVwYWYWnVe6hK133YSLDuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});